# Generated by Django 3.2.7 on 2021-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
