# Generated by Django 3.2.7 on 2021-10-05 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 12, 47, 9, 672172))),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
