# Generated by Django 3.2.7 on 2021-09-26 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 26, 18, 45, 43, 793836)),
        ),
    ]
