# Generated by Django 3.2.7 on 2021-09-28 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0006_auto_20210929_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 2, 23, 40, 596988)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
